# Generated by Django 5.0.14 on 2026-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
